# Generated by Django 3.2.5 on 2022-05-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Books', 'Books'), ('Electronics', 'Electronics')], max_length=200, null=True),
        ),
    ]
